Improve data format
KenFujita/p0f pull request #1
Opened 2019-01-08 08:38 UTC by KenFujita

- フロー毎にSYNデータとHTTP requestを紐づけた

2019-01-08 09:57 UTC, dictav commented on p0f.c
> +                       struct packet_flow* pf) {
f を pf への rename は今回の変更とは関係なさそうなので戻してもらって良いですか？

2019-01-08 09:57 UTC, dictav commented on p0f.c
> +         Also, this retusns something stupid on Windows, but hey... */
typo し直し？？
戻しましょう

2019-01-08 09:58 UTC, dictav commented on p0f.c
> +    /* PCAP timeouts tend to be broken, so we'll use a minimum value
ここも戻して良いかな

2019-01-08 09:59 UTC, dictav commented on p0f.c
> +    pt = pcap_open_live((char*)use_iface, SNAPLEN, set_promisc, 1, pcap_err);
これは意図的な変更ですか？

2019-01-08 09:59 UTC, dictav commented on p0f.c
> +    /* We use a 250 ms timeout to keep Ctrl-C responsive without resortng to
コメントも戻した方が良さそう

2019-01-08 09:59 UTC, dictav commented on p0f.c
> +    pret = poll(pfds, pfd_count, 250);
意図的な変更ですか？

2019-01-08 10:00 UTC, dictav commented on process.h
> +void C_PY(void);
要らないやつかな？

2019-01-08 10:01 UTC, dictav commented on process.c
> +  else
これは意図的な変更ですか？

2019-01-08 10:01 UTC, dictav commented on process.c
> +  WARN("Too many host entries, deleting %u. Use -m to adjust.", kcnt);
これは意図的な変更ですか？

2019-01-08 10:01 UTC, dictav commented on process.c
> +  bucket = hash32(&pk->sport, 2, hash_seed) ^ hash32(&pk->dport, 2, hash_seed);
これは意図的な変更ですか？

2019-01-08 10:01 UTC, dictav commented on process.c
これは意図的な変更ですか？

2019-01-08 10:02 UTC, dictav commented on process.c
> +        if (*data != 4) {
場所が移動している。戻した方が良さそうです。

2019-01-08 10:02 UTC, dictav commented on process.c
> +        if (*data != 3) {
場所が移動している。戻した方が良さそうです。

2019-01-08 10:02 UTC, dictav commented on process.c
> +        if (*data != 2) {
場所が移動している。戻した方が良さそうです。

2019-01-08 10:02 UTC, dictav commented on process.c
> +        if (data + 9 > opt_end) {
場所が移動している。戻した方が良さそうです。

2019-01-08 10:03 UTC, dictav commented on process.c
戻した方が良さそうです。

2019-01-08 10:03 UTC, dictav commented on fp_http.c
> +    if (!memcmp(hdr_names[*p], name, len) &&
戻した方が良さそうです。

2019-01-18 01:53 UTC, KenFujita commented on p0f.c
> +    pt = pcap_open_live((char*)use_iface, SNAPLEN, set_promisc, 1, pcap_err);
意図的な変更ではありません。戻した方がいいですか？

2019-01-18 01:54 UTC, KenFujita commented on p0f.c
> +    pret = poll(pfds, pfd_count, 250);
これも意図的に変更はしていません。

2019-01-18 01:55 UTC, KenFujita commented on process.h
> +void C_PY(void);
使わなくなった関数なので削除します。

2019-01-18 01:55 UTC, KenFujita commented on process.c
> +  else
これも意図的な変更ではありません。

2019-01-18 01:56 UTC, KenFujita commented on process.c
> +  WARN("Too many host entries, deleting %u. Use -m to adjust.", kcnt);
これも意図的な変更ではありません。

2019-01-18 01:56 UTC, KenFujita commented on process.c
> +  bucket = hash32(&pk->sport, 2, hash_seed) ^ hash32(&pk->dport, 2, hash_seed);
これも意図的な変更ではありません。

2019-01-18 01:56 UTC, KenFujita commented on process.c
これも意図的な変更ではありません。

2019-01-18 02:36 UTC, KenFujita commented
意図していない変更を元の状態(masterブランチの状態)に戻しました。

2019-01-18 04:51 UTC, dictav commented on p0f.c
> +    pt = pcap_open_live((char*)use_iface, SNAPLEN, set_promisc, 1, pcap_err);
用途がはっきりわかっていて、5 ではなく 1 が正しいのであれば戻す必要はありません。
そうでなければ戻した方が良いと思います、

2019-01-18 04:52 UTC, dictav commented on p0f.c
> +    pret = poll(pfds, pfd_count, 250);
用途がはっきりわかっていて、5 ではなく 1 が正しいのであれば戻す必要はありません。
そうでなければ戻した方が良いと思います。

2019-01-18 04:53 UTC, dictav commented on fp_http.c
> +    if (!memcmp(hdr_names[*p], name, len) /* ASAN won't like this... */ &&
これも戻した方が良さそう

2019-01-18 05:02 UTC, dictav requested changes

2019-01-18 05:02 UTC, dictav commented on p0f.c
> +      if (pfds[cur].revents & (POLLERR | POLLHUP)) switch (cur) {
位置がずれたように見えます。戻した方が良さそうです。

2019-01-18 05:02 UTC, dictav commented on p0f.c
> +  SAYF("--- p0f"  VERSION  " by Michal Zalewski <lcamtuf@coredump.cx> ---\n\n");
これも関係なさそう

2019-01-18 05:02 UTC, dictav commented on p0f.c
> +        FATAL("Even more promiscuous? People will call me slutty!");
コメントが変わったのかな？
関係なさそう

2019-01-18 05:02 UTC, dictav commented on p0f.h
> -extern u8* read_file;
これも戻した方が良さそう。
ないとコンパイルできないんじゃないかな？

2019-01-18 05:02 UTC, dictav commented on p0f.h
> +                       struct packet_flow* f);
これも戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +#include <Python.h>
Python は使わないよね？？

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (*data != 4) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (*data != 3) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +          DEBUG("[#] MSS option expected to have 3 bytes, not %u.\n", *data);
`MMS` の方が正しい？？
わからなければ戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (*data != 2) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (data == opt_end) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (data + 9 > opt_end) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +
タブの不要な追加？
戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (*data != 10) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (data == opt_end) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +        }
タブの不要な追加？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +	if (*data < 2 || *data > 40) {
スペースからタブに変わった？
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +      // This is about as far as we want to go with p0f-sendsyn.
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.c
> +
本件とは関係ないので戻した方が良さそう

2019-01-18 05:02 UTC, dictav commented on process.h
> +
本件とは関係ないので戻した方が良さそう

2019-01-18 05:03 UTC, dictav commented
上記指摘部分、解決済みのものは resolve ボタンを押すと折り畳んで見やすくしてくれると思います

2019-01-18 05:52 UTC, KenFujita commented on p0f.h
> -extern u8* read_file;
おっしゃる通り、消したらコンパイルできなくなったので戻しました。

2019-01-18 06:29 UTC, KenFujita commented
**delete some padding**
- タブをスペースに戻しました。
- 使わないライブラリ(Python.h)を削除しました。
- 1部コメントを変更しました。
- コンパイルができるようにread_fileの宣言を変更しました。
- その他p0fの動作に関係ない変更をなくしました。

2019-01-18 06:52 UTC, KenFujita commented
**delete not need code and add p0f function**
- if文の判定式の変更、コメントアウトしていた箇所の削除を行いました。
- SYNパケットのシグネチャとp0fの結果、それに対応するHTTPのリクエストをまとめたクエリに対して、エスケープ記号(¥r¥n)を別の記号(,や.)に置換するための関数を宣言しました。

2019-01-22 06:36 UTC, KenFujita commented
**delete the charactor of escape**
- replace_escapeという関数を作成し、HTTPリクエストにあるエスケープ文字(改行記号、¥r¥n)を取り除きクエリとして扱えるようにしました。
- その他コメントを追加しました。

2019-01-25 08:05 UTC, KenFujita commented
**improve function of replace_escape**
- 渡したポインタの中身からエスケープ記号を直接取り除くため、[replace_escape関数](https://github.com/KenFujita/p0f/blob/improve_data_format/process.c#L1135)の引数、処理内容を変更しました。
- 各フロー毎のSYNシグネチャとHTTPリクエストを紐づけるため、[プログラム](https://github.com/KenFujita/p0f/blob/improve_data_format/process.c#L1398)を変更しました。

2019-01-25 08:51 UTC, KenFujita commented
**delete else if(before_fn == flow_num)**
- [https://github.com/KenFujita/p0f/blob/improve_data_format/process.c#L1398](https://github.com/KenFujita/p0f/blob/improve_data_format/process.c#L1398)にて、else if(before_fn == flow_num)によってフローごとのSYNパケットとHTTPリクエストを紐づけられないため削除しました

2019-01-28 03:31 UTC, KenFujita commented
**improve signature data format**
- 一つのフローごとにHTTPリクエストを関連付けしました。
    - 文字列操作をしやすくするため、変数fp_sigの型をcharポインタからchar配列に変更しました。
- 不要な変数、コメントを削除しました。

2019-03-22 02:32 UTC, merged